### ISSUE TITLE
{#vote for feature&function}

### ISSUE THREAD

**Issue by Lozyboobob** [WeAreOpenSourceProjects/Storytelling#424]
@PierreBrisorgueil @farhatmo @cherifa-ghersi 

1. -x add a return btn in slides presentation page
2. - [ ] the filter for "favorite/public/private" is not clear, replace the drop down list with checkbox
3. - [ ] in slides editor, use enter to input tag (now when the input lose focus will automatically create a tag)
4. - [ ] in presentation, we may delete the title page (the first page generated automatically), and put the title of slides in the hearder bar
5. - [ ] give a maximum length limit to slides description
6. - [ ] new feature: comment on slides

**Comment by PierreBrisorgueil** [comment]
1 👎  no :p 
2 why not
3 👍 but maybe we need to wait for an update of angular material no ? maybe it's already fixed in the new version ? 
4 👍 if I understand this, is to add in the topnav the title of the actual presentation ? if yes it's a feature of stack v1, we have a page-title directive who calculate the top title with the road, the object, and bonus params in the road, you can have a look on the article page of romeanet for this if you want
5 👍 
6 👍 yes but maybe not yet, bu I think we need to talk about coms on a presentation, with a like system, not on a slide :) but cool next step, I'm agree !
